name: CI
on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container: alpine:latest
    env:
      PLATFORM: linux64
      OPAMYES: 1

    steps:
      - name: Install dependencies
        run: |
          set -ex
          apk update
          apk add --no-cache bash curl tar xz build-base musl-dev zlib-dev pcre2-dev mbedtls-dev \
            git opam ocaml ocaml-compiler-libs ocaml-findlib ocamlbuild make cmake \
            gtk+2.0-dev perl perl-utils ninja coreutils

      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Build and Install Neko
        run : |
          curl -LkSs https://github.com/HaxeFoundation/neko/archive/refs/tags/v2-4-1.tar.gz | gzip -d | tar -x
          cd neko-2-4-1
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DSTATIC_DEPS=all -DBUILD_SHARED_LIBS=OFF -DSTATIC_BOEHMGC=ON -DCMAKE_EXE_LINKER_FLAGS="-static" 
          make -j$(nproc)
          make install
          neko -version 2>&1

      - name: Install OCaml libraries
        run: |
          set -ex
          export CC=musl-gcc
          opam init --bare --disable-sandboxing
          opam update
          opam switch create 4.14.2+muslnative+flambda+static ocaml-variants.${{ matrix.ocaml }}+options ocaml-option-flambda ocaml-option-static
          eval $(opam env --switch=4.14.2+muslnative+flambda+static)
          opam pin add haxe . --no-action
          opam install -y haxe --deps-only --assume-depexts
          opam list
          ocamlopt -v

      - name: Set ADD_REVISION=1 for non-release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "ADD_REVISION=1" >> $GITHUB_ENV

      - name: Build Haxe
        run: |
          set -ex
          export CC=musl-gcc
          eval $(opam env --switch=4.14.2+muslnative+flambda+static)
          make STATICLINK=1 -s -j$(nproc) haxe haxelib package_unix
          ls -l out
          ldd ./haxe || true
          ldd ./haxelib || true

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Build xmldoc
        if: matrix.ocaml == '4.14.0'
        run: |
          set -ex
          make -s xmldoc
          cat >extra/doc/info.json <<EOL
            {
              "commit": "$GITHUB_SHA",
              "branch": "${{ steps.extract_branch.outputs.branch }}"
            }
          EOL

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxBinaries${{ (matrix.ocaml == '5.3.0' && '_ocaml5') || '' }}
          path: out

      - name: Upload xmldoc artifact
        uses: actions/upload-artifact@v4
        if: matrix.ocaml == '4.14.0'
        with:
          name: xmldoc
          path: extra/doc

  linux-arm64-build:
    runs-on: ubuntu-24.04-arm
    container: arm64v8/alpine:latest
    env:
      PLATFORM: linux-arm64
      OPAMYES: 1

    steps:
      - name: Install dependencies
        run: |
          set -ex
          apk update
          apk add --no-cache bash curl tar xz build-base musl-dev zlib-dev pcre2-dev mbedtls-dev \
            git opam ocaml ocaml-compiler-libs ocaml-findlib ocamlbuild make cmake \
            gtk+2.0-dev perl perl-utils ninja coreutils

      # - uses: actions/checkout@main
        # with:
          # submodules: recursive

      - name: Build and Install Neko
        run : |
          curl -LkSs https://github.com/HaxeFoundation/neko/archive/refs/tags/v2-4-1.tar.gz | gzip -d | tar -x
          cd neko-2-4-1
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DSTATIC_DEPS=all -DBUILD_SHARED_LIBS=OFF -DSTATIC_BOEHMGC=ON -DCMAKE_EXE_LINKER_FLAGS="-static" 
          make -j$(nproc)
          make install
          neko -version 2>&1

      - name: Install OCaml libraries
        run: |
          set -ex
          export CC=musl-gcc
          opam init --bare --disable-sandboxing
          opam update
          opam switch create 4.14.2+muslnative+flambda+static ocaml-variants.4.13.1+options ocaml-option-flambda ocaml-option-static
          eval $(opam env --switch=4.14.2+muslnative+flambda+static)
          opam pin add haxe . --no-action
          opam install -y haxe --deps-only --assume-depexts
          opam list
          ocamlopt -v

      - name: Set ADD_REVISION=1 for non-release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "ADD_REVISION=1" >> $GITHUB_ENV

      - name: Build Haxe
        run: |
          set -ex
          export CC=musl-gcc
          eval $(opam env --switch=4.14.2+muslnative+flambda+static)
          make STATICLINK=1 -s -j$(nproc) haxe haxelib package_unix
          ls -l out
          ldd ./haxe || true
          ldd ./haxelib || true

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxArm64Binaries
          path: out
