name: CI
on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container: alpine:latest
    env:
      PLATFORM: linux64
      OPAMYES: 1
      ZIG_TARGET: x86_64-linux-musl
    strategy:
      fail-fast: false
      matrix:
        ocaml: ["4.14.0"]

    steps:
      - name: Install dependencies
        run: |
          set -ex
          apk update
          apk add --no-cache bash curl tar xz build-base musl-dev zlib-dev pcre2-dev mbedtls-dev \
            git opam ocaml ocaml-compiler-libs ocaml-findlib ocamlbuild make \
            gtk+2.0-dev perl perl-utils ninja coreutils neko

      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Cache opam
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: /root/.opam/
          key: alpine-${{ matrix.ocaml }}-${{ hashFiles('./haxe.opam', './libs/') }}

      - name: Print Neko version
        run: neko -version 2>&1

      - name: Install OCaml libraries
        if: steps.cache-opam.outputs.cache-hit != 'true'
        run: |
          set -ex
          export CC=musl-gcc
          opam init --bare --disable-sandboxing
          opam update
          opam switch create ${{ matrix.ocaml }}+muslnative+flambda ocaml-variants.${{ matrix.ocaml }}+options ocaml-option-flambda ocaml-option-musl ocaml-option-static
          eval $(opam env --switch=${{ matrix.ocaml }}+muslnative+flambda)
          opam pin add haxe . --no-action
          opam install -y haxe --deps-only --assume-depexts
          opam list
          ocamlopt -v

      - name: Set ADD_REVISION=1 for non-release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "ADD_REVISION=1" >> $GITHUB_ENV

      - name: Build Haxe
        run: |
          set -ex
          export CC=musl-gcc
          eval $(opam env --switch=${{ matrix.ocaml }}+muslnative+flambda)
          make STATICLINK=1 -s -j$(nproc) haxe haxelib package_unix
          ls -l out
          ldd ./haxe || true
          ldd ./haxelib || true

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Build xmldoc
        if: matrix.ocaml == '4.14.0'
        run: |
          set -ex
          make -s xmldoc
          cat >extra/doc/info.json <<EOL
            {
              "commit": "$GITHUB_SHA",
              "branch": "${{ steps.extract_branch.outputs.branch }}"
            }
          EOL

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxBinaries${{ (matrix.ocaml == '5.3.0' && '_ocaml5') || '' }}
          path: out

      - name: Upload xmldoc artifact
        uses: actions/upload-artifact@v4
        if: matrix.ocaml == '4.14.0'
        with:
          name: xmldoc
          path: extra/doc

  linux-arm64-build:
    runs-on: ubuntu-latest
    container: arm64v8/alpine:latest
    env:
      PLATFORM: linux-arm64
      OPAMYES: 1
      ZIG_TARGET: aarch64-linux-musl

    steps:
      - name: Install dependencies
        run: |
          set -ex
          apk update
          apk add --no-cache bash curl tar xz build-base musl-dev zlib-dev pcre2-dev mbedtls-dev \
            git opam ocaml ocaml-compiler-libs ocaml-findlib ocamlbuild make \
            gtk+2.0-dev perl perl-utils ninja coreutils neko

      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Cache opam
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: /root/.opam/
          key: alpine-arm64-${{ hashFiles('./haxe.opam', './libs/') }}

      - name: Print Neko version
        run: neko -version 2>&1

      - name: Install OCaml libraries
        if: steps.cache-opam.outputs.cache-hit != 'true'
        run: |
          set -ex
          export CC=musl-gcc
          opam init --bare --disable-sandboxing
          opam update
          opam switch create 4.13.1+muslnative+flambda ocaml-variants.4.13.1+options ocaml-option-flambda ocaml-option-musl ocaml-option-static
          eval $(opam env --switch=4.13.1+muslnative+flambda)
          opam pin add haxe . --no-action
          opam install -y haxe --deps-only --assume-depexts
          opam list
          ocamlopt -v

      - name: Set ADD_REVISION=1 for non-release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "ADD_REVISION=1" >> $GITHUB_ENV

      - name: Build Haxe
        run: |
          set -ex
          export CC=musl-gcc
          eval $(opam env --switch=4.13.1+muslnative+flambda)
          make STATICLINK=1 -s -j$(nproc) haxe haxelib package_unix
          ls -l out
          ldd ./haxe || true
          ldd ./haxelib || true

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxArm64Binaries
          path: out
